apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/deployment.yml
- ../../base/service.yml
namespace: fha-dev
images:
  - name: fouadhamdi/springboot-sample-app
    newTag: 1.0.1

