apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-sample-app-dev
spec:
  destination:
    namespace: fha-dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ops/overlays/fha-dev
    repoURL: https://github.com/fouadh/springboot-sample-app.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
