apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: springboot-sample-app
spec:
  builder:
    name: paketo-builder
    kind: Builder
  serviceAccount: kpack-bot
  source:
    git:
      url: https://github.com/fouadh/springboot-sample-app
      revision: master
  tag: fouadhamdi/springboot-sample-app
