apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: springboot-sample-app
  name: springboot-sample-app
spec:
  ports:
  - name: 7777-8080
    port: 7777
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot-sample-app
  type: ClusterIP
status:
  loadBalancer: {}
