apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/deployment.yml
- ../../base/service.yml
namespace: fha-prod
patchesStrategicMerge:
- env.yml
commonLabels:
  env: prod